CREATE TABLE IF NOT EXISTS snmp_targets (
    id INT AUTO_INCREMENT PRIMARY KEY,
    label VARCHAR(64) NOT NULL,
    ip_address VARCHAR(64) NOT NULL,
    community VARCHAR(64) NOT NULL DEFAULT 'public',
    oid_str VARCHAR(128) NOT NULL,
    last_value VARCHAR(256) DEFAULT NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    alert_flag TINYINT(1) NOT NULL DEFAULT 0,
    last_updated TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

